"""Change default is_active to False for new admins

Revision ID: ac3a65fdfb5e
Revises: 772df6fd9902
Create Date: 2026-02-25 16:41:27.185509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3a65fdfb5e'
down_revision = '772df6fd9902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household')
    op.drop_table('spatial_ref_sys')
    op.drop_table('household_survey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_survey',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_mun_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('barangay_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ean', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bsn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('husn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hsn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('q14_toilet_facility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('household_survey_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('household',
    sa.Column('region_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('province_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('city_mun_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('barangay_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ean', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bsn', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('husn', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hsn', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('q14_toilet_facility', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
